---
# get volume ID
- name: get volume ID from the EC2 instance
  ec2_vol:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}" 
    instance: "{{ source_instance_id }}"
    snapshot: "{{ snapshot_id }}"
    device_name: "{{ my_device_name }}"
  register: ec2_vol

- debug:
    msg: "{{ ec2_vol.volume_id }}"
    
# detach a volume 
- name: detach a volume from the EC2 instance
  ec2_vol:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}" 
    id: "{{ ec2_vol.volume_id }}"
    instance: None    
