---
# tasks file for create-ec2-machine
- name: "create EC2 machine {{ instance_name }}-{{ tag_name }}"
  ec2:
     aws_access_key: "{{ aws_access_key }}"
     aws_secret_key: "{{ aws_secret_key }}"
     key_name: "{{ keypair }}"
     instance_type: "{{ instance_type }}"
     region: "{{ region }}"
     image: "{{ image }}"
     instance_profile_name: "{{ iam_role }}"
     wait: yes
     volumes:
      - device_name: /dev/sda1
        volume_type: io1
        iops: 3000
        volume_size: 100
      - device_name: /dev/sda2
        snapshot: "{{ snapshot_id }}"
        volume_type: io1
        iops: 3000
        volume_size: 100
     group: "{{ security_group }}"
     instance_tags:
        Name: "{{ instance_name }}-{{ tag_name }}"
     exact_count: "{{ count }}"
     count_tag: "{{ tag_name }}"
     vpc_subnet_id: "{{ vpc_subnet_id }}"
     assign_public_ip: yes
  register: ec2

